dist: trusty
sudo: required

language: generic

services:
  - docker

matrix:
  include:
   - env: CODECEPTION_SUITE=mandatory
   - env: CODECEPTION_SUITE=essential
  allow_failures:
   - env: CODECEPTION_SUITE=essential

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.13.0
    - STACK_PHP_IMAGE=testing/phd5-template

before_install:
  - sudo rm /usr/local/bin/docker-compose || true
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - cp .env-dist .env
  - make all

script:
  - make test

after_script:
  - make clean
