# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '3.2'
services:

  php:

    ports:
      - '80'
    depends_on:
      - db
      - redis
      - mailcatcher
    environment:
      # Development ONLY settings
      - DB_ENV_MYSQL_ROOT_PASSWORD=secret
      - GITHUB_API_TOKEN
      - ENV_LOCAL_FILE=../project/config/local.env
      - APP_ADMIN_EMAIL=admin@dev.local

    volumes:
      # Application source-code
      - ./project/:/app/project:cached
      # Vendor source-code
      - ./vendor-dev:/app/vendor:delegated
      # For composer usage in container; NOTE! There may be performance issues, see also https://github.com/docker/for-mac/issues/77
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./web/images:/app/web/images:delegated

  db:
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'

  mailcatcher:
    image: tophfr/mailcatcher:0.6.5_2
    ports:
      - '80'
