version: '3.2'

services:
  test-php:
    depends_on:
      - chrome
  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    # workaround for Docker Beta, see https://github.com/SeleniumHQ/docker-selenium/issues/227#issuecomment-224865735
    dns: 8.8.4.4
    environment:
      - no_proxy=localhost
      - VNC_NO_PASSWORD=1
    ports:
      - '4444'
      - '5900'
