# Test stack overrides
# ====================
#
# Paths in this file are relative to the project root

version: '3.2'
services:

  php:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 80
    depends_on:
      - db
      - redis
      - mailcatcher
    environment:
      # migration lookup is used from environment to switch between project and app tests (eg. gitlab-ci.yml)
      - APP_MIGRATION_LOOKUP
    volumes:
      - ../project:/app/project


  test-php:
    build: ..
    working_dir: /app/project/tests
    ports:
      - 80
    depends_on:
      - db
      - redis
      - mailcatcher
    env_file:
      - ../project/tests/env-defaults
    environment:
      # migration lookup is used from environment to switch between project and app tests (eg. gitlab-ci.yml)
      - APP_MIGRATION_LOOKUP
      - APP_ADMIN_EMAIL=admin@test.local
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ../project/tests:/app/project/tests
      - ../vendor-dev:/app/vendor
      - ../_host-volumes/app-tests-log:/app/tests/_log
      - ../_host-volumes/project-tests-log:/app/project/tests/_log
    networks:
      default:
        aliases:
          - web

  db:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - '80'
