# Test stack overrides
# ====================
#
# Paths in this file are relative to the project root

version: '3.2'
services:

  project-test-php:
    build: .
    working_dir: /app/project/tests
    ports:
      - 80
    depends_on:
      - db
      - redis
      - mailcatcher
    env_file:
      - ./project/tests/env-defaults
    environment:
      - APP_MIGRATION_LOOKUP=/app/project/tests/codeception/_migrations/data
      - APP_CONFIG_FILE=/app/project/config/main.php,/app/project/tests/codeception/_config/test.php
      - APP_ADMIN_EMAIL=admin@project-test.local
      - APP_NAME=project-test
      - PHP_ENABLE_XDEBUG=1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./project/tests:/app/project/tests
      - ./vendor-dev:/app/vendor
      - ./_host-volumes/project-tests-log:/app/project/tests/_log
    networks:
      default:
        aliases:
          - project
